export const cities = [
    "Delhi","Mumbai","Bengaluru","Kolkata","Chennai","Hyderabad","Pune","Ahmedabad","Jaipur",
    "Surat","Kanpur","Nagpur","Lucknow","Indore","Thane","Bhopal","Visakhapatnam","Vadodara",
    "Firozabad","Ludhiana","Rajkot","Agra","Siliguri","Nashik","Faridabad","Patna","Meerut",
    "Kalyan","Vasai","Varanasi","Srinagar","Aurangabad","Dhanbad","Amritsar","Navi Mumbai",
    "Allahabad","Ranchi","Howrah","Coimbatore","Jabalpur","Gwalior","Vijayawada","Jodhpur",
    "Madurai","Raipur","Kota","Chandigarh","Guwahati","Solapur","Hubli","Dharwad","Bareilly",
    "Moradabad","Mysuru","Gurgaon","Aligarh","Jalandhar","Tiruchirappalli","Bhubaneswar",
    "Salem","Warangal","Guntur","Bhiwandi","Saharanpur","Gorakhpur","Bikaner","Amravati",
    "Noida","Jamshedpur","Bhilai","Cuttack","Firozpur","Kochi","Thiruvananthapuram",
    "Dehradun","Asansol","Nanded","Kolhapur","Ajmer","Gulbarga","Loni","Ulhasnagar",
    "Jhansi","Jammu","Sangli","Mangalore","Erode","Belgaum","Kurnool","Ambattur","Tirunelveli",
    "Malegaon","Gaya","Udaipur","Tiruppur","Thanjavur","Kollam","Bokaro","Bellary","Patiala",
    "Bhavnagar","Ujjain","Tumkur","Rohtak","Panipat","Darbhanga","Muzaffarpur","Kakinada",
    "Akola","Jalgaon","Gaya","Haridwar","Shimla","Sikar","Bilaspur","Satna","Rewa","Agartala",
    "Imphal","Aizawl","Kohima","Gangtok","Itanagar","Port Blair","Puducherry","Diu","Daman",
    "Jorhat","Sambalpur","Rourkela","Balasore","Baripada","Berhampur","Puri","Hazaribagh",
    "Chhapra","Bettiah","Katihar","Begusarai","Hajipur","Motihari","Siwan","Arrah",
    "Farrukhabad","Shahjahanpur","Rampur","Etawah","Unnao","Sitapur","Ballia","Basti",
    "Deoria","Morena","Sehore","Sagar","Damoh","Chhindwara","Betul","Hoshangabad","Neemuch",
    "Ratlam","Barwani","Khandwa","Dhule","Nandurbar","Parbhani","Latur","Osmanabad","Beed",
    "Hingoli","Washim","Yavatmal","Wardha","Chandrapur","Gondia","Bhandara","Rajahmundry",
    "Eluru","Ongole","Nellore","Tirupati","Kadapa","Anantapur","Proddatur","Karimnagar",
    "Khammam","Nizamabad","Mahbubnagar","Adilabad","Suryapet","Miryalaguda","Hosur",
    "Vellore","Salem","Erode","Karur","Namakkal","Dindigul","Tanjore","Sivakasi","Thoothukudi",
    "Cuddalore","Pudukkottai","Ariyalur","Tiruvannamalai","Kanchipuram","Karaikal","Nagercoil",
    "Palakkad","Thrissur","Kottayam","Pathanamthitta","Alappuzha","Kannur","Kasaragod",
    "Kozhikode","Malappuram","Wayanad","Ernakulam","Jammu","Anantnag","Baramulla","Kupwara",
    "Leh","Kargil","Ropar","Mohali","Bathinda","Mansa","Barnala","Fazilka","Hoshiarpur",
    "Kapurthala","Nawanshahr","Pathankot","Muktsar","Sirsa","Hisar","Bhiwani","Rewari",
    "Jhajjar","Mahendragarh","Narnaul","Kurukshetra","Ambala","Karnal","Kaithal","Yamunanagar",
    "Palwal","Panaji","Margao","Mapusa","Vasco da Gama","Ponda","Jamnagar","Porbandar",
    "Anand","Nadiad","Bhuj","Gandhidham","Navsari","Valsad","Godhra","Dahod","Mehsana",
    "Patan","Himmatnagar","Junagadh","Veraval","Deesa","Modasa","Raigarh","Korba","Bilaspur",
    "Jagdalpur","Ambikapur","Koriya","Dhamtari","Mahasamund","Kawardha","Rajnandgaon",
    "Chirimiri","Nawapara","Bastar","Palamu","Gumla","Simdega","Daltonganj","Deoghar","Dumka",
    "Jamtara","Sahebganj","Pakur","Latehar","Chandil","Bardhaman","Bankura","Hooghly",
    "Malda","Murshidabad","Cooch Behar","Jalpaiguri","Darjeeling","Alipurduar","Kharagpur",
    "Haldia","Medinipur","Krishnanagar","Nabadwip","Kalyani","Raiganj","Islampur","Tezpur",
    "Silchar","Dibrugarh","Tinsukia","Bongaigaon","Nagaon","Hailakandi","Karimganj","Diphu",
    "Lumding","Rangia","Bihpuria","Lakhimpur"
    ]
    